version: 2

submodules:
  include:
     - SuiteSparse
     - eigen
  recursive: true

python:
    version: 3.9
    install:
       - method: pip
         path: .
         extra_requirements:
            - docs
