version: 2.1

executors:
    gcc_8:
        docker:
            - image: gcc:8
jobs:
    compile_gcc8:
        executor: gcc_8
        steps:
            - checkout
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U grid2op
                    cd lightsim2grid
                    git submodule init
                    git submodule update
                    make
                    python setup.py build
                    python -m pip install -U .

workflows:
    version: 2.1
    compile:
        jobs:
          - compile_gcc8
