version: 2.1

executors:
    gcc_8:
        docker:
            - image: gcc:8
    gcc_7:
        docker:
            - image: gcc:7
    gcc_6:
        docker:
            - image: gcc:6

jobs:
    compile_gcc8:
        executor: gcc_8
        steps:
            - checkout
            - run: apt-get update && apt-get install python3-pip -y
            - run: python3 -m pip install virtualenv
            - run: python3 -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U grid2op
                    pip install -U pybind11
                    git submodule init
                    git submodule update
                    make
                    CC=gcc python setup.py build
                    python -m pip install -U .

workflows:
    version: 2.1
    compile:
        jobs:
          - compile_gcc8
