name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  manylinux_build:
    name: Build linux ${{ matrix.python.name }} wheel
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python:
          - {
            name: cp37,
            abi: cp37m,
            version: '3.7',
          }
          - {
            name: cp38,
            abi: cp38,
            version: '3.8',
          }
          - {
            name: cp39,
            abi: cp39,
            version: '3.9',
          }

    steps:

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup path
        run: echo "/opt/python/${{ matrix.python.name }}-${{ matrix.python.abi }}/bin/" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Compile SuiteSparse
        run: make

      - name: Build wheel
        run: |
          python3 setup.py bdist_wheel
          auditwheel repair dist/*.whl

      - name: Install wheel
        run: pip3 install wheelhouse/*.whl --user

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: lightsim2grid-wheel-linux-${{ matrix.python.name }}
          path: wheelhouse/*.whl

  macos_windows_build:
    name: Build ${{ matrix.config.name }} ${{ matrix.python.name }} wheel
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: darwin,
            os: macos-latest,
          }
          - {
            name: windows,
            os: windows-latest,
          }
        python:
          - {
            name: cp37,
            version: '3.7',
          }
          - {
            name: cp38,
            version: '3.8',
          }
          - {
            name: cp39,
            version: '3.9',
          }

    steps:

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Compile SuiteSparse
        if: matrix.config.name == 'darwin'
        run: make
        
      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Build source archive
        if: matrix.config.name == 'darwin' && matrix.python.name == 'cp39'
        run: python setup.py sdist

      - name: Install wheel
        shell: bash
        run: python -m pip install dist/*.whl --user

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: lightsim2grid-wheel-${{ matrix.config.name }}-${{ matrix.python.name }}
          path: dist/*.whl

      - name: Upload source archive
        uses: actions/upload-artifact@v2
        if: matrix.config.name == 'darwin' && matrix.python.name == 'cp39'
        with:
          name: lightsim2grid-sources
          path: dist/*.tar.gz

  package:
    name: Package wheels
    runs-on: ubuntu-latest
    needs: [manylinux_build, macos_windows_build]

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          path: download

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: lightsim2grid-wheels
          path: |
            download/**/*.whl
            download/**/*.tar.gz
